Repository jump-dev/MathOptInterface.jl, pull requests merged in 2019-05, with the labels that each got.

#722 Remove cache from BridgeOptimizer
  src/Bridges/Bridges.jl
  src/Bridges/bridgeoptimizer.jl
  src/Bridges/flip_sign_bridge.jl
  src/Bridges/functionize_bridge.jl
  src/Bridges/intervalbridge.jl
  src/Bridges/lazybridgeoptimizer.jl
  src/Bridges/quadtosocbridge.jl
  src/Bridges/scalarizebridge.jl
  src/Bridges/singlebridgeoptimizer.jl
  src/Bridges/slackbridge.jl
  src/Bridges/vectorizebridge.jl
  src/Test/contlinear.jl
  src/Test/contquadratic.jl
  src/Utilities/functions.jl
  src/Utilities/model.jl
  src/Utilities/universalfallback.jl
  test/Bridges/Bridges.jl
  test/Bridges/external.jl
  test/Bridges/flip_sign_bridge.jl
  test/Bridges/functionize_bridge.jl
  test/Bridges/intervalbridge.jl
  test/Bridges/lazybridgeoptimizer.jl
  test/Bridges/quadtosocbridge.jl
  test/Bridges/scalarizebridge.jl
  test/Bridges/slackbridge.jl
  test/Bridges/utilities.jl
  test/Bridges/vectorizebridge.jl
  test/Utilities/functions.jl
Labels: breaking

#729 resultindex -> result_index
  src/attributes.jl
Labels: breaking

#730 Add bridge_constraint
  docs/src/apireference.md
  src/Bridges/bridge.jl
  src/Bridges/bridgeoptimizer.jl
  src/Bridges/detbridge.jl
  src/Bridges/flip_sign_bridge.jl
  src/Bridges/functionize_bridge.jl
  src/Bridges/geomeanbridge.jl
  src/Bridges/intervalbridge.jl
  src/Bridges/quadtosocbridge.jl
  src/Bridges/rsocbridge.jl
  src/Bridges/scalarizebridge.jl
  src/Bridges/slackbridge.jl
  src/Bridges/soctopsdbridge.jl
  src/Bridges/squarepsdbridge.jl
  src/Bridges/vectorizebridge.jl
Labels: Bridges, breaking

#732 SingleVariable constraint have same index as the variable
  docs/src/apimanual.md
  docs/src/apireference.md
  src/Bridges/bridgeoptimizer.jl
  src/Bridges/lazybridgeoptimizer.jl
  src/Bridges/singlebridgeoptimizer.jl
  src/Test/UnitTests/constraints.jl
  src/Test/UnitTests/modifications.jl
  src/Test/UnitTests/objectives.jl
  src/Test/UnitTests/variables.jl
  src/Test/contconic.jl
  src/Test/contlinear.jl
  src/Test/contquadratic.jl
  src/Test/intconic.jl
  src/Test/intlinear.jl
  src/Test/modellike.jl
  src/Test/nlp.jl
  src/Utilities/mockoptimizer.jl
  src/Utilities/model.jl
  src/Utilities/universalfallback.jl
  src/attributes.jl
  src/constraints.jl
  src/indextypes.jl
  test/Bridges/lazybridgeoptimizer.jl
  test/Bridges/simple_model.jl
  test/Bridges/utilities.jl
  test/Utilities/cachingoptimizer.jl
  test/Utilities/copy.jl
  test/Utilities/model.jl
  test/Utilities/parser.jl
  test/Utilities/universalfallback.jl
  test/hygiene.jl
  test/model.jl
  test/model_for_mock.jl
Labels: breaking

#738 Implement ConstraintFunction and ConstraintSet for ScalarizeBridge
  src/Bridges/scalarizebridge.jl
  src/Utilities/functions.jl
  test/Bridges/scalarizebridge.jl
Labels: Bridges

#740 Rename constant to constant_vector
  src/Utilities/functions.jl
  test/Utilities/functions.jl
Labels: breaking

#712 Indicator bridge
  docs/src/apireference.md
  src/Bridges/Bridges.jl
  src/Bridges/indicatorbridge.jl
  src/Test/intlinear.jl
  test/Bridges/Bridges.jl
  test/Bridges/indicator_bridge.jl
  test/Bridges/lazybridgeoptimizer.jl
Labels: Bridges
