Repository jump-dev/MathOptInterface.jl, pull requests merged in 2021-11, with the labels that each got.

#1649 Fix tests names
  src/Test/test_conic.jl
  src/Test/test_solve.jl
  test/Utilities/CleverDicts.jl
Labels: breaking

#1655 [Bridges] throw better error for nonconvex quadratic constraints
  src/Bridges/Constraint/quad_to_soc.jl
  test/Bridges/Constraint/quad_to_soc.jl
Labels: Submodule: Bridges

#1662 [Test] add version_added to better control MOI.Test.runtests
  docs/src/submodules/Test/overview.md
  docs/src/submodules/Test/reference.md
  src/Test/Test.jl
  src/Test/test_conic.jl
  src/Test/test_solve.jl
  test/Test/Test.jl
Labels: Submodule: Tests

#1667 [Test] update for generic coefficient types
  src/Test/test_basic_constraint.jl
Labels: Submodule: Tests

#1660 Add docs and tests for infeasibility certificates
  docs/make.jl
  docs/src/background/infeasibility_certificates.md
  src/Bridges/Constraint/scalarize.jl
  src/Test/test_infeasibility_certificates.jl
  src/Utilities/results.jl
Labels: Type: Documentation

#1673 [Test] add config.infeasible_status
  src/Test/Test.jl
  src/Test/test_conic.jl
  src/Test/test_constraint.jl
  src/Test/test_infeasibility_certificates.jl
  src/Test/test_linear.jl
  src/Test/test_solve.jl
Labels: Submodule: Tests

#1668 [Test] add generic number types in test_linear
  src/Test/Test.jl
  src/Test/test_linear.jl
  test/Test/Test.jl
Labels: Submodule: Tests

#1674 [Utilities] use ConstraintPrimal fallback in CachingOptimizer
  src/Utilities/cachingoptimizer.jl
  test/Utilities/cachingoptimizer.jl
Labels: Submodule: Utilities

#1676 [Test] add generic number types in test_constraint
  src/Test/test_constraint.jl
  src/Test/test_variable.jl
  test/Test/Test.jl
Labels: Submodule: Tests

#1677 [Utilities] Support generic number type in MockOptimizer
  src/Utilities/mockoptimizer.jl
  test/Bridges/bridge_optimizer.jl
  test/Test/Test.jl
  test/Utilities/cachingoptimizer.jl
  test/instantiate.jl
Labels: Submodule: Utilities

#1672 [Utilities] fix fallback of map_indices
  src/Utilities/cachingoptimizer.jl
  src/Utilities/copy.jl
  src/Utilities/functions.jl
  src/Utilities/mockoptimizer.jl
  test/Utilities/cachingoptimizer.jl
Labels: Submodule: Utilities

#1680 [Test] simplify type check in test_nonlinear
  src/Test/test_nonlinear.jl
Labels: Submodule: Tests

#1686 [Test] fix test_model_copy_to_ tests
  src/Test/test_model.jl
Labels: Submodule: Tests

#1689 [Test] fix missing config in _test_det_cone_helper
  src/Test/test_conic.jl
Labels: Submodule: Tests
