Repository jump-dev/MathOptInterface.jl, pull requests merged in 2021-08, with the labels that each got.

#1499 [breaking] re-order fields of QuadraticFunction
  src/Bridges/Constraint/soc_to_nonconvex_quad.jl
  src/DeprecatedTest/UnitTests/basic_constraint_tests.jl
  src/DeprecatedTest/UnitTests/constraints.jl
  src/DeprecatedTest/UnitTests/objectives.jl
  src/DeprecatedTest/contquadratic.jl
  src/DeprecatedTest/nlp.jl
  src/FileFormats/MOF/read.jl
  src/Test/test_basic_constraint.jl
  src/Test/test_constraint.jl
  src/Test/test_nonlinear.jl
  src/Test/test_objective.jl
  src/Test/test_quadratic.jl
  src/Utilities/functions.jl
  src/Utilities/mutable_arithmetics.jl
  src/Utilities/parser.jl
  src/deprecate.jl
  src/functions.jl
  test/Bridges/Constraint/quad_to_soc.jl
  test/FileFormats/NL/NL.jl
  test/Utilities/functions.jl
  test/Utilities/model.jl
  test/Utilities/parser.jl
  test/Utilities/print.jl
  test/deprecate.jl
  test/functions.jl
Labels: breaking

#1491 [breaking] remove index_value function
  src/indextypes.jl
Labels: breaking

#1461 Fix StackOverflow with self-loop bridges
  src/Bridges/Constraint/set_map.jl
  src/Bridges/Constraint/single_bridge_optimizer.jl
  src/Bridges/Objective/single_bridge_optimizer.jl
  src/Bridges/Variable/set_map.jl
  src/Bridges/Variable/single_bridge_optimizer.jl
  src/Bridges/bridge_optimizer.jl
  src/Bridges/lazy_bridge_optimizer.jl
  test/Bridges/bridge_optimizer.jl
  test/Bridges/identity_bridge.jl
Labels: breaking

#1283 Add MOI.attribute_value_type
  docs/src/reference/models.md
  docs/src/tutorials/implementing.md
  src/Bridges/Constraint/bridge.jl
  src/Bridges/Constraint/det.jl
  src/Bridges/Constraint/functionize.jl
  src/Bridges/Constraint/geomean.jl
  src/Bridges/Constraint/geomean_to_relentr.jl
  src/Bridges/Constraint/indicator_sos.jl
  src/Bridges/Constraint/interval.jl
  src/Bridges/Constraint/norm_spec_nuc_to_psd.jl
  src/Bridges/Constraint/norm_to_lp.jl
  src/Bridges/Constraint/quad_to_soc.jl
  src/Bridges/Constraint/relentr_to_exp.jl
  src/Bridges/Constraint/scalarize.jl
  src/Bridges/Constraint/semi_to_binary.jl
  src/Bridges/Constraint/set_map.jl
  src/Bridges/Constraint/slack.jl
  src/Bridges/Constraint/soc_to_nonconvex_quad.jl
  src/Bridges/Constraint/square.jl
  src/Bridges/Constraint/vectorize.jl
  src/Bridges/Constraint/zero_one.jl
  src/Bridges/Objective/functionize.jl
  src/Bridges/Objective/slack.jl
  src/Bridges/Variable/free.jl
  src/Bridges/Variable/rsoc_to_psd.jl
  src/Bridges/Variable/set_map.jl
  src/Bridges/Variable/vectorize.jl
  src/Bridges/Variable/zeros.jl
  src/Bridges/bridge.jl
  src/Bridges/bridge_optimizer.jl
  src/DeprecatedTest/modellike.jl
  src/Test/Test.jl
  src/Test/test_attribute.jl
  src/Test/test_basic_constraint.jl
  src/Test/test_linear.jl
  src/Test/test_model.jl
  src/Test/test_objective.jl
  src/Test/test_solve.jl
  src/Test/test_variable.jl
  src/Utilities/cachingoptimizer.jl
  src/Utilities/functions.jl
  src/Utilities/model.jl
  src/Utilities/struct_of_constraints.jl
  src/Utilities/universalfallback.jl
  src/Utilities/vector_bounds.jl
  src/Utilities/vector_of_constraints.jl
  src/attributes.jl
  test/attributes.jl
Labels: breaking, Submodule: Utilities, Type: Performance

#1515 [Test] Fix requires in ObjectiveBound tests
  src/Test/test_solve.jl
Labels: Submodule: Tests

#1516 [Test] Add test for NLPBlockDual
  src/Test/test_nonlinear.jl
Labels: Submodule: Tests

#1517 [Test] fix bug in skipping ConstraintDual
  src/Test/Test.jl
Labels: Type: Bug, Submodule: Tests

#1518 [Test] add a test for attributes after empty
  src/Test/test_attribute.jl
Labels: Submodule: Tests

#1512 [breaking] remove automatic_copy_to
  docs/src/submodules/Utilities/reference.md
  docs/src/tutorials/implementing.md
  src/Bridges/bridge_optimizer.jl
  src/Utilities/copy.jl
  src/Utilities/mockoptimizer.jl
  src/Utilities/model.jl
  src/Utilities/universalfallback.jl
  test/DeprecatedTest/modellike.jl
  test/Utilities/cachingoptimizer.jl
  test/Utilities/copy.jl
  test/deprecate.jl
  test/dummy.jl
Labels: breaking

#1525 Remove unneeded deletions
  src/Utilities/model.jl
Labels: Submodule: Utilities

#1523 Rename .variable_bounds to .variables
  src/Utilities/model.jl
Labels: Submodule: Utilities

#1526 [Utilities] Rename variable and objective containers
  docs/src/submodules/Bridges/overview.md
  docs/src/submodules/FileFormats/overview.md
  docs/src/submodules/Utilities/overview.md
  src/Utilities/Utilities.jl
  src/Utilities/model.jl
  src/Utilities/objective_container.jl
  src/Utilities/variables_container.jl
  test/Utilities/copy.jl
  test/Utilities/matrix_of_constraints.jl
  test/Utilities/model.jl
  test/Utilities/objective_container.jl
  test/Utilities/variable_container.jl
Labels: Submodule: Utilities

#1530 Improve documentation of IndexMap
  docs/src/reference/models.md
  src/MathOptInterface.jl
  src/Utilities/copy/index_map.jl
Labels: Submodule: Utilities

#1536 [Test] Add test for NLP without objective
  src/Test/test_nonlinear.jl
Labels: Submodule: Tests

#1537 [Test] Add test for NaN in NLP callbacks
  src/Test/test_nonlinear.jl
Labels: Submodule: Tests

#1535 Remove copy_names argument
  docs/src/submodules/Utilities/overview.md
  docs/src/tutorials/implementing.md
  src/Bridges/bridge_optimizer.jl
  src/DeprecatedTest/contconic.jl
  src/DeprecatedTest/contlinear.jl
  src/DeprecatedTest/contquadratic.jl
  src/DeprecatedTest/intconic.jl
  src/DeprecatedTest/intlinear.jl
  src/DeprecatedTest/modellike.jl
  src/FileFormats/NL/NL.jl
  src/MathOptInterface.jl
  src/Test/test_conic.jl
  src/Test/test_linear.jl
  src/Test/test_model.jl
  src/Test/test_quadratic.jl
  src/Utilities/cachingoptimizer.jl
  src/Utilities/copy.jl
  src/Utilities/mockoptimizer.jl
  src/Utilities/model.jl
  src/Utilities/universalfallback.jl
  src/instantiate.jl
  test/Utilities/cachingoptimizer.jl
  test/Utilities/copy.jl
  test/deprecate.jl
  test/dummy.jl
  test/instantiate.jl
Labels: breaking, Submodule: Utilities

#1540 [Bridges] tidy quad_to_soc.jl
  src/Bridges/Constraint/quad_to_soc.jl
  test/Bridges/Constraint/quad_to_soc.jl
Labels: Submodule: Bridges

#1539 [Test] add compute_conflict tests from Gurobi.jl
  src/Test/test_solve.jl
  src/Utilities/mockoptimizer.jl
  test/Utilities/cachingoptimizer.jl
Labels: Submodule: Tests

#1544 [Bridges] Maintenance of GeoMeanBridge
  src/Bridges/Constraint/geomean.jl
  src/Utilities/functions.jl
Labels: Submodule: Bridges

#1552 [Test] Add more tests from Gurobi.jl
  src/Test/test_objective.jl
  src/Test/test_solve.jl
Labels: Submodule: Tests

#1550 Clarify ConstraintPrimal for conic solvers
  docs/src/reference/standard_form.md
  src/attributes.jl
Labels: Type: Documentation
